# ⚠️ **Important Disclaimer**

Do **not edit or delete** any of the **Markdown cells** (the ones containing the questions and instructions).

Only write your answers in the **code cells provided below each question**.  
This ensures consistency during our feedback process.

### Q1. Load and Explore the Dataset

Load the `AirQalityDataset.csv` file into a pandas DataFrame using the correct separator.

After loading the data:

1. Display basic information about the dataset.
2. Save the statistical description of the dataset into a separate variable.
3. Drop fully empty/unnamed columns, and rows
4. Use `type()` to print the type of that description variable.

In [139]:
import pandas as pd
import numpy as np 
np.random.seed(0)


In [132]:
# your Code Here
# Load the CSV file from C:\MDA\2025\Term_1\Python for data Analysis (CPSC 610-2)\Assignment_2\AirQualityDataset.csv"
airqualitydataset = pd.read_csv(r"C:\MDA\2025\Term_1\Python for data Analysis (CPSC 610-2)\Assignment_2\AirQualityDataset.csv", sep=";")
airqualitydataset.head()

# Basic information about the dataset
print('\nAirquality Information:')
airquality_info = airqualitydataset.info()
airquality_stats = airqualitydataset.describe()

# Drop fully empty rows & columns
airqualitydataset_dropped = airqualitydataset.dropna(axis=1, how='all')
airqualitydataset_dropped = airqualitydataset_dropped.dropna(how='all')

# Basic information about the dataset
print('\nAirquality Information Dropped:')
airqualitydataset_dropped.info()

# Looking for missing values
missing_values= airqualitydataset.isnull().sum()
print('\nMissing Values on airqualitydataset:')
print(missing_values[missing_values > 0])

missing_values_dropped = airqualitydataset_dropped.isnull().sum()
print('\nMissing Values Dropped:')
print(missing_values_dropped[missing_values_dropped > 0])

# Use type() to show description variable
print('\nType of airquality dataset:')
print(type(airqualitydataset))
print('\nType of airquality dataset dropped:')
print(type(airqualitydataset_dropped))



Airquality Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(15), object(2)
m

### Q2. Dataset structure and features overview  
Write a code to collect:
1. The number of rows and columns in the dataset.
2. The list of first 10 feature columns excluding `'Date'` and `'Time'`.  

Store both lists in tuple called `dataset_info` and print it.

In [59]:
# your Code Here
# Number of rows and columns
num_rows, num_cols = airqualitydataset_dropped.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)
# List the first 10 columns after date and time
print("\nFirst 10 columns after date and time:")
print(airqualitydataset_dropped.columns[2:12])

# Set both lists in a tuple called dataset_info
dataset_info = (num_rows, num_cols, airqualitydataset_dropped.columns[2:12])
print("\nDataset Info Tuple:")
print(dataset_info)

Number of rows: 9357
Number of columns: 15

First 10 columns after date and time:
Index(['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)',
       'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)'],
      dtype='object')

Dataset Info Tuple:
(9357, 15, Index(['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)',
       'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)'],
      dtype='object'))


### Q3. CO(GT) summary with Pandas and NumPy
Compute the **mean** and **standard deviation** of `CO(GT)` using both:
- Pandas
- NumPy

In [61]:
# your Code Here
# Using pandas to compute mean and standard deviation of CO(GT) column
co_gt_mean = airqualitydataset_dropped['CO(GT)'].mean()
co_gt_std = airqualitydataset_dropped['CO(GT)'].std()
print("\nPandas CO(GT) Mean:", co_gt_mean)
print("Pandas CO(GT) Standard Deviation:", co_gt_std)
# Using numpy to compute mean and standard deviation of CO(GT) column
co_gt_mean_np = np.mean(airqualitydataset_dropped['CO(GT)'])
co_gt_std_np = np.std(airqualitydataset_dropped['CO(GT)'])
print('\nNumpy CO(GT) Mean:', co_gt_mean_np)
print('Numpy CO(GT) Standard Deviation:', co_gt_std_np)



Pandas CO(GT) Mean: -34.207523778989
Pandas CO(GT) Standard Deviation: 77.65717034682939

Numpy CO(GT) Mean: -34.207523778989
Numpy CO(GT) Standard Deviation: 77.65302055280891


### Q4. Absolute humidity (AH) distribution  
Compute the **min**, **median**, and **max** of `AH` using Pandas.  

Do you notice an issue in the values?  
If you think that there are values that are problematic, replace them with the median of the column and print the same three statistics after that.


In [70]:
# your Code Here
# Computing min, max and median value of AH
AH_min = airqualitydataset_dropped['AH'].min()
print('AH_min value:', AH_min)
AH_max = airqualitydataset_dropped['AH'].max()
print('\nAH_max value:', AH_max)
AH_median = airqualitydataset_dropped['AH'].median()
print('\nAH_median value:', AH_median)

# There were negative values in the AH column, so I replaced them with the median of the column

# Replacing negative values on AH column with the median
airqualitydataset_dropped['AH'] = airqualitydataset_dropped['AH'].mask(airqualitydataset_dropped['AH'] < 0, AH_median)



AH_min value: 0.1847

AH_max value: 2.231

AH_median value: 0.9768


### Q5. Humidity bands
Create a new column `humidity_band` using `RH`:
- `'dry'` if `RH < 30`
- `'comfortable'` if `30 <= RH <= 60`
- `'humid'` if `RH > 60`

Then show the **count** of each category.

In [71]:
# your Code Here
# Defining a function to categorize humidity levels
def humidity_band(RH):
    if RH < 30:
        return 'dry'
    elif 30 <= RH <= 60:
        return 'comfortable'
    else:
        return 'humid'

# Applying the function to create a new column
airqualitydataset_dropped['humidity_band'] = airqualitydataset_dropped['RH'].apply(humidity_band)
airqualitydataset_dropped.head()


Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9   
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4   
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0   
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2   
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   

      T    RH      AH humidity_band  
0  13.6  48.9  0.7578   comfortable  
1  13.3  47.7  0.7255   comfortable  
2  11.9  54.0  0.7502   comfortable  
3  11.0  60.0  0.7867   comfortable  
4  11.2  59.6  0.7888   comfortable

### Q6. Compute the Average 'CO(GT)' for Humid Conditions  

Using the `'humidity_band'` column created above, filter the dataset for rows labeled `'humid'` and compute the **average value of `'CO(GT)'`** for these observations.  

Format the output to 4 decimal places for better readability and precision.

In [77]:
# your Code Here
# filter the dataset for 'humid' humidity levels
humid_days = airqualitydataset_dropped[airqualitydataset_dropped['humidity_band'] == 'humid']
humid_co_mean = humid_days['CO(GT)'].mean()
print("\nMean CO(GT) for humid days:", humid_co_mean.round(4))



Mean CO(GT) for humid days: -35.5567


### Q7. Retrieve and sort array by a specific column
Create a NumPy array from the columns `[T, RH, AH]` (in this order), then sort the array by the **third column (`AH`)** ascending. Show the first 5 rows.

In [82]:
# your Code Here
array = airqualitydataset_dropped[['T', 'RH', 'AH']].to_numpy()
# First 5 rows of the array
print('\nArray:')
print(array[:5])
# Sorting the array by the AH column
array_sorted = array[array[:, 2].argsort()]
print("\nSorted Array by AH Column:")
# First 5 rows
print(array_sorted[:5])


Array:
[[13.6    48.9     0.7578]
 [13.3    47.7     0.7255]
 [11.9    54.      0.7502]
 [11.     60.      0.7867]
 [11.2    59.6     0.7888]]

Sorted Array by AH Column:
[[ 0.     29.7     0.1847]
 [11.8    13.5     0.1862]
 [ 0.2    30.2     0.191 ]
 [-0.1    31.9     0.1975]
 [12.2    14.      0.1988]]


### Q8. Normalized moisture index

Using the NumPy array you built above (**Do not change it**):  

1. Using Numpy, **Convert RH to a fraction** (0–1 scale) by dividing it by 100 and save it to another array `RH_frac`.
2. Using Numpy, **Compute a normalized moisture index** by dividing `AH` by `RH_frac`. This almost computes the amount of absolute humidity per unit of relative humidity.

Print the first 10 values of this new array and then **store** the result in the original DataFrame as a new column `'moisture_index'`.

In [97]:
# your Code Here
# Creating new array 'RH_frac'
RH_frac = array[:, 1] / 100
print('\n First 10 values for RH_frac:')
print(RH_frac[:10])  # Displaying the first 10 values of RH_frac

# Normalized moisture index
n_moisture_index = array[:, 2] / RH_frac
print('\n First 10 values for moisture_index array:')
print(n_moisture_index[:10])

# store the results in the original dataframe
airqualitydataset_dropped['moisture_index'] =  n_moisture_index
airqualitydataset_dropped.head(10)

# I had to use the first array ' array' for the calculations instead of 'array_sorted' to maintain the original order of the data.


 First 10 values for RH_frac:
[0.489 0.477 0.54  0.6   0.596 0.592 0.568 0.6   0.597 0.602]

 First 10 values for moisture_index array:
[1.54969325 1.52096436 1.38925926 1.31116667 1.32348993 1.32567568
 1.33855634 1.28366667 1.28107203 1.2486711 ]


Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9   
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4   
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0   
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2   
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5   
5  10/03/2004  23.00.00     1.2       1197.0      38.0       4.7   
6  11/03/2004  00.00.00     1.2       1185.0      31.0       3.6   
7  11/03/2004  01.00.00     1.0       1136.0      31.0       3.3   
8  11/03/2004  02.00.00     0.9       1094.0      24.0       2.3   
9  11/03/2004  03.00.00     0.6       1010.0      19.0       1.7   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   
5          750.0     89.0        1337.0     96.0        1393.0        949.0   
6          690.0     62.0        1462.0     77.0        1333.0        733.0   
7          672.0     62.0        1453.0     76.0        1333.0        730.0   
8          609.0     45.0        1579.0     60.0        1276.0        620.0   
9          561.0   -200.0        1705.0   -200.0        1235.0        501.0   

      T    RH      AH humidity_band  moisture_index  
0  13.6  48.9  0.7578   comfortable        1.549693  
1  13.3  47.7  0.7255   comfortable        1.520964  
2  11.9  54.0  0.7502   comfortable        1.389259  
3  11.0  60.0  0.7867   comfortable        1.311167  
4  11.2  59.6  0.7888   comfortable        1.323490  
5  11.2  59.2  0.7848   comfortable        1.325676  
6  11.3  56.8  0.7603   comfortable        1.338556  
7  10.7  60.0  0.7702   comfortable        1.283667  
8  10.7  59.7  0.7648   comfortable        1.281072  
9  10.3  60.2  0.7517         humid        1.248671

### Q9. Temperature profile for high moisture index  

Using Numpy only, and the `moisture_index` values you computed earlier:  

1. Find the **median** of `moisture_index`.  
2. Filter `tri_array` to include only rows where `moisture_index` is above this median.  
3. Compute and print the **mean temperature** for this high-moisture group using only NumPy.

Format the output to 4 decimal places for better readability and precision.

In [110]:
# your Code Here
# Find the median value of n_moisture_index array using numpy
n_moisture_index_median = np.median(n_moisture_index)
print("\nMedian of n_moisture_index:", n_moisture_index_median.round(4))

# Reshape n_moisture_index to a column vector
n_moisture_index_col = n_moisture_index.reshape(-1, 1)

# Concatenate as a new column to the original array
array_with_moisture_index = np.concatenate((array, n_moisture_index_col), axis=1)

# Print the first 5 rows to verify
print("\nArray with Moisture Index [T, RH, AH, Moisture Index]:")
print(array_with_moisture_index[:5].round(4))

# Filtered array for rows where moisture index is above the median
filtered_array = array_with_moisture_index[array_with_moisture_index[:, 3] > n_moisture_index_median]
print("\nFiltered Array (Moisture Index > Median):")
print(filtered_array.round(4))

# Mean temperature
mean_temperature = filtered_array[:, 0].mean()
print("\nMean Temperature (T) for Filtered Array:", mean_temperature.round(4))




Median of n_moisture_index: 1.9457

Array with Moisture Index [T, RH, AH, Moisture Index]:
[[13.6    48.9     0.7578  1.5497]
 [13.3    47.7     0.7255  1.521 ]
 [11.9    54.      0.7502  1.3893]
 [11.     60.      0.7867  1.3112]
 [11.2    59.6     0.7888  1.3235]]

Filtered Array (Moisture Index > Median):
[[18.4    33.8     0.709   2.0976]
 [19.4    31.3     0.695   2.2204]
 [18.     34.8     0.7127  2.048 ]
 ...
 [26.9    18.3     0.6406  3.5005]
 [28.3    13.5     0.5139  3.8067]
 [28.5    13.1     0.5028  3.8382]]

Mean Temperature (T) for Filtered Array: 25.2345


### Q10. Percentile-based filtering
Compute:
- the **85th percentile** of `C6H6(GT)` (benzene), and
- the **25th percentile** of `RH`.

Filter and return rows where `C6H6(GT)` is **above** its 85th percentile **and** `RH` is **below** its 25th percentile. Show the number of rows and the first 5 matches.


In [121]:
# your Code Here
# 85th percentile for C6H6(GT)
c6h6_85th_percentile = airqualitydataset_dropped['C6H6(GT)'].quantile(0.85)
print("\n85th Percentile for C6H6(GT):", c6h6_85th_percentile.round(4))

# 25th percentile for RH
rh_25th_percentile = airqualitydataset_dropped['RH'].quantile(0.25)
print("\n25th Percentile for RH:", rh_25th_percentile.round(4))

# Filtered rows where C6H6(GT) > 85th percentile and RH < 25th percentile
filtered_airquality = airqualitydataset_dropped[(airqualitydataset_dropped['C6H6(GT)'] > c6h6_85th_percentile) 
                                                & (airqualitydataset_dropped['RH'] < rh_25th_percentile)]

print('\nNumber of rows in Filtered Air Quality Data:', filtered_airquality.shape[0])
print("\nFiltered Air Quality Data where 'C6H6(GT) > 85th percentile and RH < 25th percentile':")
filtered_airquality.head()



85th Percentile for C6H6(GT): 17.3

25th Percentile for RH: 34.1

Number of rows in Filtered Air Quality Data: 276

Filtered Air Quality Data where 'C6H6(GT) > 85th percentile and RH < 25th percentile':


Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
137  16/03/2004  11.00.00     4.1       1571.0     327.0      20.0   
138  16/03/2004  12.00.00     3.3       1452.0     283.0      18.3   
139  16/03/2004  13.00.00     4.0       1579.0     366.0      22.3   
140  16/03/2004  14.00.00     3.8       1466.0     318.0      20.4   
144  16/03/2004  18.00.00     3.4       1447.0     237.0      17.8   

     PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
137         1297.0    314.0         730.0    162.0        1973.0       1729.0   
138         1250.0    217.0         776.0    154.0        1868.0       1583.0   
139         1359.0    252.0         724.0    161.0        1998.0       1671.0   
140         1309.0    263.0         773.0    161.0        1897.0       1491.0   
144         1235.0    184.0         859.0    139.0        1778.0       1296.0   

        T    RH      AH humidity_band  moisture_index  
137  21.4  33.3  0.8417   comfortable        2.527628  
138  24.4  27.4  0.8231           dry        3.004015  
139  25.3  26.1  0.8264           dry        3.166284  
140  25.8  23.2  0.7589           dry        3.271121  
144  23.9  25.7  0.7519           dry        2.925681

### Q11. Simulate Sensor Measurement Noise and Analyze the Effect  

Simulate **normally distributed measurement noise** with a mean of `0` and a standard deviation of `100` (in raw sensor units). Then:  

- Use **NumPy** to generate the noise.  
- Use **Pandas** to add this noise to the `'PT08.S1(CO)'` column and store the result in a new column `'PT08.S1_noisy'`.  
- Print the **mean** and **standard deviation** of both `'PT08.S1(CO)'` and `'PT08.S1_noisy'` to observe the impact of the simulated noise.  

Observe how the added noise affects the distribution, particularly the spread (**standard deviation**). Format all printed values to **4 decimal places** using `.4f`.  


In [145]:
# your Code Here
# Simulate normally distributed measurement noise
np.random.seed(0)  # For reproducibility
noise = np.random.normal(loc=0, scale=100, size=airqualitydataset_dropped['PT08.S1(CO)'].shape)

# Add noise to the PT08.S1(CO) column
airqualitydataset_dropped['PT08.S1_noisy'] = airqualitydataset_dropped['PT08.S1(CO)'] + noise

# Print mean and std for both columns, formatted to 4 decimals
mean_original = airqualitydataset_dropped['PT08.S1(CO)'].mean()
std_original = airqualitydataset_dropped['PT08.S1(CO)'].std()
mean_noisy = airqualitydataset_dropped['PT08.S1_noisy'].mean()
std_noisy = airqualitydataset_dropped['PT08.S1_noisy'].std()

print(f"Mean of PT08.S1(CO): {mean_original:.4f}")
print(f"Mean of PT08.S1_noisy: {mean_noisy:.4f}")
print(f"Std of PT08.S1(CO): {std_original:.4f}")
print(f"Std of PT08.S1_noisy: {std_noisy:.4f}")

Mean of PT08.S1(CO): 1048.9901
Mean of PT08.S1_noisy: 1046.8703
Std of PT08.S1(CO): 329.8327
Std of PT08.S1_noisy: 345.1911


# Make Your Results Reproducible

If you re-run the previous cell multiple times, you'll notice that the results involving randomness (e.g., simulated noise) change each time. This is because NumPy generates new random numbers on every execution.

To make your results **reproducible** (meaning that both you and your instructor get the **same output every time**) you need to set a fixed **random seed**.

As the final task, go back and add the following line to your code **immediately after importing NumPy** for the first time in your notebook:

```python
np.random.seed(0)


So, your NumPy import at the top of the notebook should now look like this:

```python
import numpy as np
np.random.seed(0)


# After Making This Change:

- Re-run **all cells** in the notebook from top to bottom.  
- Make sure **all outputs are visible**.  
- **Save your notebook.**  
- **Submit it as-is (with all outputs included.)**
